import logo from "/assets/images/logo.jpeg";
import search from "/assets/images/search.svg";
import nasa from "/assets/images/nasa.svg";
import usArmy from "/assets/images/usa.svg";
import target from "/assets/images/target-charcoal.svg";
import tiffany from "/assets/images/Tiffany-charcoal.svg";
import jpl from "/assets/images/JPL-charcoal.svg";
import bcg from "/assets/images/BCG-charcoal.svg";
import slide1 from "/assets/images/slide-1.jpeg";
import slide2 from "/assets/images/architecture-img.jpeg";
import slide3 from "/assets/images/cad-design-img.jpeg";
import slide4 from "/assets/images/invention-img.jpeg";
import slide5 from "/assets/images/product-design-img.jpeg";
import slide6 from "/assets/images/3d-rendering-img.jpeg";
import slide7 from "/assets/images/consumer-products-img.jpeg";
import slide8 from "/assets/images/engineering-img.jpeg";
import slide9 from "/assets/images/manufacturing-img.jpeg";
import slide10 from "/assets/images/patent-drawings-img.jpg";
import slide11 from "/assets/images/more-cad-services-img.jpg";
import cadIcon from "/assets/images/services-cad.svg";
import designIcon from "/assets/images/services-design-contest.svg";
import contestIcon from "/assets/images/services-3d-cad-design.svg";
import industrialIcon from "/assets/images/services-industrial-design.svg";
import productIcon from "/assets/images/services-product-design.svg";
import architecturalIcon from "/assets/images/services-architecture.svg";
import ideaIcon from "/assets/images/services-patent-drawings.svg";
import manufactureIcon from "/assets/images/services-manufacturing.svg";
import graphic1 from "/assets/images/graphic-hire.svg";
import graphic2 from "/assets/images/graphic-contests.svg";
import graphic3 from "/assets/images/graphic-hourly.svg";
import contactBG from "/assets/images/bg.svg";
import slider1 from "@/assets/slider3.jpg";
import slider2 from "@/assets/slider2.jpg";
import slider3 from "@/assets/slider1.jpg";
import slider4 from "/assets/images/image-4.jpg";
import slider5 from "/assets/images/image-5.jpg";
import slider6 from "/assets/images/image-6.jpg";
import highway from "/assets/images/highway.jpg";
import twoD from "/assets/images/2d.png";
import threeD from "/assets/images/3d.png";
import bill from "/assets/images/bill.jpg";
import coordination from "/assets/images/coordination.jpg";
import designValidation from "/assets/images/design-validation.jpeg";
import drawing from "/assets/images/drawing-services.jpg";
import field from "/assets/images/field-survey.jpeg";

export const logoImg = logo;
export const searchImg = search;
export const nasaImg = nasa;
export const usArmyImg = usArmy;
export const targetImg = target;
export const tiffanyImg = tiffany;
export const jplImg = jpl;
export const bcgImg = bcg;
export const slideImg1 = slide1;
export const slideImg2 = slide2;
export const slideImg3 = slide3;
export const slideImg4 = slide4;
export const slideImg5 = slide5;
export const slideImg6 = slide6;
export const slideImg7 = slide7;
export const slideImg8 = slide8;
export const slideImg9 = slide9;
export const slideImg10 = slide10;
export const slideImg11 = slide11;
export const cadIconImg = cadIcon;
export const designIconImg = designIcon;
export const contestIconImg = contestIcon;
export const industrialIconImg = industrialIcon;
export const productIconImg = productIcon;
export const architecturalIconImg = architecturalIcon;
export const ideaIconImg = ideaIcon;
export const manufactureIconImg = manufactureIcon;
export const graphic1Img = graphic1;
export const graphic2Img = graphic2;
export const graphic3Img = graphic3;
export const contactBGImg = contactBG;
export const slider1Img = slider1;
export const slider2Img = slider2;
export const slider3Img = slider3;
export const slider4Img = slider4;
export const slider5Img = slider5;
export const slider6Img = slider6;
export const highwayImg = highway;
export const twoDImg = twoD;
export const threeDImg = threeD;
export const billImg = bill;
export const coordinationImg = coordination;
export const designValidationImg = designValidation;
export const drawingImg = drawing;
export const fieldImg = field;


